### ISSUE TITLE
Не все числа правильно

### ISSUE THREAD

**Issue by spogozhev** [Cr1msonEdge/computer-practice#1]
https://github.com/Cr1msonEdge/computer-practice/blob/0acc076cc131e10943d053973a80c1fec3f375a5/homework/1.11.2021/homework_01.11.2021_4.cpp#L253

Проверьте, например, 1013 или 1111.

**Comment by Cr1msonEdge** [comment]
Загрузил новую версию. Тогда загрузил файл с ошибкой, исправил, исправленное не выложил
