### ISSUE TITLE
Не работает для элементов менее 10^-2

### ISSUE THREAD

**Issue by spogozhev** [Cr1msonEdge/computer-practice#3]
https://github.com/Cr1msonEdge/computer-practice/blob/3cb8e791c18997e1155d68c76a6ff5d328debbe0/homework/2021.11.22/matrix.cpp#L142-L143

Нельзя так преобразовывать элементы матрицы при вычислении определителей!

**Comment by Cr1msonEdge** [comment]
Исправлено
